---
openapi: "3.0.1"
info:
  title: "SearchCustomerDocuments"
  version: "v1"
servers:
- url: "{server}/prweb/api/CustomerDocuments/v1"
  description: "Default Application"
  variables:
    server:
      default: "https://dev-rfs-02.rulesware.com"
tags:
- name: "Int-OBAB-NBE-Docs"
paths:
  /SearchCustomerDocuments:
    get:
      tags:
      - "Int-OBAB-NBE-Docs"
      summary: ""
      parameters:
      - name: "SearchKey"
        in: "query"
        allowEmptyValue: true
        schema:
          type: "string"
      - name: "SearchValue"
        in: "query"
        allowEmptyValue: true
        schema:
          type: "string"
      responses:
        default:
          description: ""
          content:
            application/json:
              schema:
                type: "string"
    put:
      tags:
      - "Int-OBAB-NBE-Docs"
      summary: ""
      parameters:
      - name: "hola"
        in: "header"
        allowEmptyValue: true
        schema:
          $ref: "#/components/schemas/_unknown"
      responses:
        200:
          description: "test"
          content:
            application/json:
              schema:
                type: "string"
                enum:
                - "test"
components:
  schemas:
    _unknown:
      title: "Unknown"